create table skillsets
(
    id                   serial primary key,
    shooting_dribble     smallint,
    shooting_off_dribble smallint,
    standing_dunk        smallint,
    drive_dunk           smallint,
    fade_away            smallint,
    post_hook            smallint,
    contest_shoot        smallint,
    three_point          smallint,
    free_throw           smallint,
    drive                smallint,
    pass_accuracy        smallint,
    pass_vision          smallint,
    dribbling            smallint,
    defence_rebound      smallint,
    offense_rebound      smallint,
    interior_defence     smallint,
    perimeter_defence    smallint,
    steal                smallint,
    block                smallint,
    speed                smallint,
    acceleration         smallint,
    durability           smallint,
    jump                 smallint
);